### PR TITLE
Continuous integration or Toxify all the things!!!

### PR DESCRIPTION
**Pull request by tomster**
This change introduces building and uploading the package for each commit on or merge into the master branch onto our devpi instance at https://pypi.senic.com/

Each developer fork has its own index, so there shouldn't be any versioning clashes.

### CODE REVIEW

**Comment by tomster** [comment]
Note, that merging this PR should automatically result in a package appearing at https://pypi.senic.com/senic/master (which is currently still empty)

**Comment by tomster** [comment]
Also, maybe one of you has an idea how to best implement slack notifications?

**Comment by larsblumberg** [comment]
I wouldn't be surprised if there was a Slack integration for Travis, we can pair on that

**Comment by grunskis** [comment]
LGTM! I might have more comments after trying it out.

**Pull request merged**
